-- لاگ سوال/جواب دستیار تحلیلگر (L1 trace ساده — پایه شخصی‌سازی آینده)
-- اجرا در Supabase SQL Editor / Run in Supabase SQL Editor

create table if not exists public.assistant_qa_log (
  id              bigint generated by default as identity primary key,
  user_id         uuid references auth.users (id) on delete cascade,
  question        text not null,
  answer          text,
  symbol          text,
  has_stock_data  boolean not null default false,
  sources         jsonb,
  created_at      timestamptz not null default now()
);

create index if not exists assistant_qa_log_user_idx
  on public.assistant_qa_log (user_id, created_at);

alter table public.assistant_qa_log enable row level security;

-- کاربر فقط تاریخچه سوال/جواب خودش را می‌بیند؛ درج فقط از API route با service-role
drop policy if exists "assistant_qa_log_select_own" on public.assistant_qa_log;
create policy "assistant_qa_log_select_own" on public.assistant_qa_log
  for select using (auth.uid() = user_id);
