-- بورس سنج — کامنت زیر هر نماد سهم/صندوق (بخش گفتگو/حس جمعی — فاز ۲ نقشه راه)
-- در Supabase Dashboard → SQL Editor اجرا شود

create table if not exists comments (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null references auth.users (id) on delete cascade,
  display_name text not null default 'کاربر',  -- از user_metadata خود کاربر موقع ثبت گرفته می‌شود (کلاینت نمی‌تواند auth.users را join کند)
  target_type  text not null check (target_type in ('stock', 'fund')),
  target_key   text not null,        -- نماد سهم یا slug صندوق
  body         text not null check (char_length(trim(body)) between 2 and 500),
  created_at   timestamptz not null default now()
);

create index if not exists comments_target_idx on comments (target_type, target_key, created_at desc);

alter table comments enable row level security;

-- خواندن برای همه (کامنت‌ها محتوای عمومی‌اند)
drop policy if exists "comments read" on comments;
create policy "comments read" on comments
  for select using (true);

-- ثبت فقط برای کاربر لاگین‌شده، فقط با user_id خودش
drop policy if exists "comments insert own" on comments;
create policy "comments insert own" on comments
  for insert with check (auth.uid() = user_id);

-- حذف فقط توسط خود نویسنده یا ادمین (جدول admins موجود)
drop policy if exists "comments delete own or admin" on comments;
create policy "comments delete own or admin" on comments
  for delete using (
    auth.uid() = user_id
    or exists (select 1 from admins where admins.id = auth.uid())
  );
