-- تصویر روزانه‌ی ارزش پورتفوی هر کاربر — برای عملکرد دوره‌ای و چارت روند واقعی در app/portfolio/page.tsx
-- پر شدن این جدول به‌عهده‌ی scripts/snapshot-portfolio.js (کرون روزانه روی سرور) است، نه از مرورگر کاربر.
-- اجرا در Supabase SQL Editor / Run in Supabase SQL Editor

create table if not exists public.portfolio_daily_snapshot (
  id                bigint generated by default as identity primary key,
  user_id           uuid not null references auth.users (id) on delete cascade,
  snap_date         text not null,                        -- تاریخ شمسی YYYY/MM/DD (فقط نمایشی)
  total_value       numeric not null default 0,           -- ارزش روز پورتفو به ریال
  invested_capital  numeric not null default 0,           -- بهای تمام‌شده به ریال
  created_at        timestamptz not null default now(),   -- مبنای واقعی محاسبه‌ی بازه‌های زمانی (میلادی)
  unique (user_id, snap_date)
);

create index if not exists portfolio_daily_snapshot_user_idx
  on public.portfolio_daily_snapshot (user_id, created_at);

alter table public.portfolio_daily_snapshot enable row level security;

-- فقط خواندن ردیف‌های خودش برای کاربر مجاز است؛ درج/بروزرسانی فقط با service-role از کرون سرور انجام می‌شود
drop policy if exists "portfolio_snapshot_select_own" on public.portfolio_daily_snapshot;
create policy "portfolio_snapshot_select_own" on public.portfolio_daily_snapshot
  for select using (auth.uid() = user_id);
