-- جدول تراکنش‌های پورتفوی کاربران — هر کاربر فقط ردیف‌های خودش را می‌بیند (RLS)
-- اجرا در Supabase SQL Editor / Run in Supabase SQL Editor

create table if not exists public.portfolio_transactions (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null default auth.uid() references auth.users (id) on delete cascade,
  symbol      text not null,                     -- نماد (l18 برای سهام، slug برای صندوق)
  name        text not null default '',          -- نام کامل
  asset_type  text not null default 'stock' check (asset_type in ('stock', 'fund')),
  side        text not null default 'buy'  check (side in ('buy', 'sell')),
  quantity    numeric not null check (quantity > 0),
  price       numeric not null check (price >= 0),   -- قیمت واحد به ریال
  commission  numeric not null default 0 check (commission >= 0), -- کارمزد کل تراکنش به ریال
  trade_date  text not null default '',          -- تاریخ شمسی YYYY/MM/DD
  broker      text not null default '',          -- کارگزاری (اختیاری)
  note        text not null default '',
  created_at  timestamptz not null default now()
);

create index if not exists portfolio_transactions_user_idx
  on public.portfolio_transactions (user_id, symbol);

alter table public.portfolio_transactions enable row level security;

drop policy if exists "portfolio_select_own" on public.portfolio_transactions;
create policy "portfolio_select_own" on public.portfolio_transactions
  for select using (auth.uid() = user_id);

drop policy if exists "portfolio_insert_own" on public.portfolio_transactions;
create policy "portfolio_insert_own" on public.portfolio_transactions
  for insert with check (auth.uid() = user_id);

drop policy if exists "portfolio_update_own" on public.portfolio_transactions;
create policy "portfolio_update_own" on public.portfolio_transactions
  for update using (auth.uid() = user_id);

drop policy if exists "portfolio_delete_own" on public.portfolio_transactions;
create policy "portfolio_delete_own" on public.portfolio_transactions
  for delete using (auth.uid() = user_id);
