-- تاریخچه‌ی روزانه‌ی قیمت پایانی نمادهایی که سیگنال سهام برایشان صادر شده —
-- چون stock_industries فقط اسنپ‌شات لحظه‌ای است و تاریخچه‌ی قیمت سهام جایی ذخیره نمی‌شد،
-- محاسبه‌ی «نتیجه ۱۰ روزه» سیگنال سهام بدون این جدول ممکن نیست.
-- پر شدن این جدول به‌عهده‌ی scripts/snapshot-stock-signal-prices.js (کرون روزانه) است.
-- اجرا در Supabase SQL Editor / Run in Supabase SQL Editor

create table if not exists public.stock_signal_prices (
  id          bigint generated by default as identity primary key,
  symbol      text not null,           -- l18
  snap_date   text not null,           -- تاریخ شمسی YYYY/MM/DD
  price       numeric not null,        -- قیمت پایانی (ریال)
  created_at  timestamptz not null default now(),
  unique (symbol, snap_date)
);

create index if not exists stock_signal_prices_symbol_idx
  on public.stock_signal_prices (symbol, snap_date);

alter table public.stock_signal_prices enable row level security;

-- عمومی و فقط‌خواندنی — هیچ داده‌ی کاربری در این جدول نیست
drop policy if exists "stock_signal_prices_select_all" on public.stock_signal_prices;
create policy "stock_signal_prices_select_all" on public.stock_signal_prices
  for select using (true);
