-- ربات تلگرامی پورتفوی شخصی — کد اتصال یک‌بارمصرف + جدول لینک کاربر↔چت تلگرام
-- اجرا در Supabase SQL Editor / Run in Supabase SQL Editor

create table if not exists public.telegram_link_codes (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null default auth.uid() references auth.users (id) on delete cascade,
  code_hash   text not null,
  expires_at  timestamptz not null,
  attempts    int not null default 0,
  used_at     timestamptz,
  created_at  timestamptz not null default now()
);

create index if not exists telegram_link_codes_user_idx
  on public.telegram_link_codes (user_id, created_at);

alter table public.telegram_link_codes enable row level security;

-- کاربر فقط وضعیت کدهای خودش را می‌بیند؛ درج/بروزرسانی فقط از API route با service-role
drop policy if exists "telegram_link_codes_select_own" on public.telegram_link_codes;
create policy "telegram_link_codes_select_own" on public.telegram_link_codes
  for select using (auth.uid() = user_id);

create table if not exists public.telegram_links (
  user_id            uuid primary key references auth.users (id) on delete cascade,
  telegram_chat_id   bigint not null unique,
  telegram_username  text,
  linked_at          timestamptz not null default now()
);

alter table public.telegram_links enable row level security;

-- کاربر فقط وضعیت اتصال خودش را می‌بیند؛ همه‌ی نوشتن‌ها (لینک از API route، آنلینک از بات) با service-role
drop policy if exists "telegram_links_select_own" on public.telegram_links;
create policy "telegram_links_select_own" on public.telegram_links
  for select using (auth.uid() = user_id);
